게시글번호,
게시글카테고리,
작성자,
제목,
작성일,
조회수

;
CREATE SEQUENCE SEQ_KH_BOARD;
DROP TABLE KH_BOARD;
CREATE TABLE KH_BOARD(
	BOARD_NO NUMBER PRIMARY KEY,
	BOARD_CATEGORY VARCHAR2(20) NOT NULL,
	BOARD_WRITER VARCHAR2(10) REFERENCES KH_MEMBER,
	BOARD_TITLE VARCHAR2(300) NOT NULL,
	BOARD_CONTENT VARCHAR(4000) NOT NULL,
	COUNT NUMBER DEFAULT 0,
	CREATE_DATE DATE DEFAULT SYSDATE
);
SELECT * FROM KH_BOARD;

ALTER TABLE KH_MEMBER MODIFY MEMBER_PW VARCHAR2(60);

UPDATE 
				KH_MEMBER 
	SET
				MEMBER_PW = '$2a$10$jFnJ0GneGWqMAnrv62lgz.qo4Rc.5RFTUWXTo106Poop8xiku68XC';

COMMIT;
	



-- 게시글용 테이블 구현하기
-- 파일첨부 기능 구현할 것 + 댓글 기능 구현할 것

CREATE TABLE TB_SPRING_BOARD(
	BOARD_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	
	BOARD_TITLE VARCHAR2(200) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_WRITER VARCHAR2(10) NOT NULL REFERENCES KH_MEMBER,
	COUNT NUMBER DEFAULT 0 NOT NULL, 
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	CHANGE_NAME VARCHAR2(200),
	STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
	
);


DROP TABLE TB_SPRING_BOARD;

INSERT INTO TB_SPRING_BOARD(BOARD_TITLE, BOARD_WRITER)
VALUES('두 번째 글', 'admin');
SELECT * FROM TB_SPRING_BOARD;


