CREATE TABLE TB_REPLY(
	REPLY_NO NUMBER PRIMARY KEY,
	REPLY_WRITER VARCHAR(10) NOT NULL REFERENCES KH_MEMBER,
	REPLY_CONTENT VARCHAR2(500) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	REF_BOARD_NO NUMBER NOT NULL REFERENCES TB_SPRING_BOARD
);
INSERT INTO TB_REPLY
VALUES (SEQ_RNO.NEXTVAL, 'user01', '후후후', SYSDATE, 1);
COMMIT;
CREATE SEQUENCE SEQ_RNO;
SELECT * FROM TB_REPLY;
SELECT
		  BOARD_NO boardNo
		, BOARD_TITLE boardTitle
		, BOARD_CONTENT boardContent
		, BOARD_WRITER boardWriter
		, TB_SPRING_BOARD.CREATE_DATE createDate
		, CHANGE_NAME changeName
		, REPLY_NO replyNo
		, REPLY_WRITER replyWriter
		, REPLY_CONTENT replyContent
		, REF_BOARD_NO refBoardNo
		, TB_REPLY.CREATE_DATE createDate
FROM
		TB_SPRING_BOARD
LEFT
JOIN
		TB_REPLY ON (BOARD_NO = REF_BOARD_NO)
WHERE
		BOARD_NO = 17
		
;


SELECT 
				BOARD_NO,
				BOARD_TITLE,
				BOARD_WRITER
FROM	
				TB_SPRING_BOARD 
WHERE 
				STATUS = 'Y'
AND 	
				--BOARD_WRITER LIKE '%ad%'
				--BOARD_TITLE LIKE '%마%'
				BOARD_CONTENT LIKE '%ㅎ%'
ORDER
BY 
				BOARD_NO DESC;


---------------------------------------------------------------


CREATE TABLE TB_COMMENTS(
	CONTENT VARCHAR2(1000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UC_SEQ NUMBER NOT NULL
);

SELECT * FROM TB_COMMENTS;

---------------------------------------------------------------

CREATE TABLE TB_BOOT_MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY, 
	MEMBER_ID VARCHAR2(20) NOT NULL,
	MEMBER_PW VARCHAR2(64) NOT NULL,
	MEMBER_NAME VARCHAR2(30) NOT NULL,
	ROLE VARCHAR2(15) NOT NULL
);

CREATE SEQUENCE SEQ_BM;

SELECT * FROM TB_BOOT_MEMBER ;


-- 1. 누가 토큰 발급받으면 INSERT
-- 2. 누가 AccessToken 만료되면 SELECT
-- 3. 누가 로그아웃하면 DELETE
DROP TABLE TB_BOOT_TOKEN;
CREATE TABLE TB_BOOT_TOKEN(
	TOKEN NVARCHAR2(200) NOT NULL,
	MEMBER_NO NUMBER REFERENCES TB_BOOT_MEMBER,
	EXPIRATION NUMBER
);
SELECT * FROM TB_BOOT_TOKEN;



CREATE SEQUENCE SEQ_BBN;
CREATE TABLE TB_BOOT_BOARD(
	BOARD_NO NUMBER PRIMARY KEY,	
	BOARD_TITLE NVARCHAR2(200) NOT NULL,
	BOARD_CONTENT NVARCHAR2(1000) NOT NULL,
	BOARD_WRITER NUMBER NOT NULL REFERENCES TB_BOOT_MEMBER,
	BOARD_FILE_URL NVARCHAR2(1000),
	STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
	CREATE_DATE DATE DEFAULT SYSDATE,
	MODIFY_DATE DATE DEFAULT SYSDATE
);















